### ISSUE TITLE
FEAT: Fazer a service e store de orcamentos

### ISSUE THREAD

**Issue by AnthonyLoche** [2info2-Grupo-3/FrontManutencao#22]
Fazer a service e store de orcamentos no projeto vue

**Comment by jonatasperaza** [comment]
# Feat-22
## Stores, services e erros

criei tanto a store quanto a service porem quando fui testalas percebi que tinha um erro geral de importação então já aproveitei e o corrigi voce estava importando assim:



![Image](https://github.com/user-attachments/assets/dce98732-b5b6-46c6-ab35-b22ef07638df)

Pórem ali voce diz que voce quer importar as service daquelas pastas porem só funciona quando voce tem o index então voce precisa importar uma por uma ficando assim:



![Image](https://github.com/user-attachments/assets/d64be4a6-b1f3-45f6-bf0e-7b8fbc304f4a)

fazendo isso o site já voltou deixei um console.log na home apenas para teste



![Image](https://github.com/user-attachments/assets/ffc634af-a122-4d92-9935-11c547d62c7c)

oque me retornou isso:



![Image](https://github.com/user-attachments/assets/753ccc06-f50b-442f-bf19-43a49991f85b)


e tambem não tinha o axios então já aproveite e o instalei já colocando como dependencia
